### ISSUE TITLE
intervalStack: Unable to mount with Enzyme

### ISSUE THREAD

**Issue by devilbags** [alibaba/BizCharts#209]
When trying to do a full Dom mounting of BizChart (intervalStack), test failed.

Component: (This is directly taken from the [demo](https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/pie/innerlabel))
```jsx
const PieChart = () => {
 const data = [
          { item: '事例一', count: 40 },
          { item: '事例二', count: 21 },
          { item: '事例三', count: 17 },
          { item: '事例四', count: 13 },
          { item: '事例五', count: 9 }
        ];
        const dv = new DataView();
        dv.source(data).transform({
          type: 'percent',
          field: 'count',
          dimension: 'item',
          as: 'percent'
        });
        const cols = {
          percent: {
            formatter: val => {
              val = (val * 100) + '%';
              return val;
            }
          }
        }  
  return (
<Chart height={window.innerHeight} data={dv} scale={cols} padding={[ 80, 100, 80, 80 ]} forceFit>
            <Coord type='theta' radius={0.75} />
            <Axis name="percent" />
            <Legend position='right' offsetY={-window.innerHeight / 2 + 120} offsetX={-100} />
            <Tooltip 
              showTitle={false} 
              itemTpl='<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>'
              />
            <Geom
              type="intervalStack"
              position="percent"
              color='item'
              tooltip={['item*percent',(item, percent) => {
                percent = percent * 100 + '%';
                return {
                  name: item,
                  value: percent
                };
              }]}
              style={{lineWidth: 1,stroke: '#fff'}}
              >
              <Label content='percent' offset={-40} textStyle={{
                  rotate: 0,
                  textAlign: 'center',
                  shadowBlur: 2,
                  shadowColor: 'rgba(0, 0, 0, .45)'
                }} />
            </Geom>
          </Chart>
)
}
export default PieChart
```

Test Code with Enzyme
```js
import React from 'react'
import {shallow, mount} from 'enzyme'
import PieChart from './PieChart'

it('Shallow rendering works fine of course', () => {
 shallow(<PieChart />)
})
it('Mount will fail', () => {
 mount(<PieChart />)
})
```

When try to run the above test, below error is observed:
```
TypeError: Cannot read property 'save' of null

at CText.measureText (node_modules/bizcharts/umd/BizCharts.js:8379:19)
      at CText.calculateBox (node_modules/bizcharts/umd/BizCharts.js:8260:28)
      at CText.getBBox (node_modules/bizcharts/umd/BizCharts.js:1109:24)
      at node_modules/bizcharts/umd/BizCharts.js:6150:32
      at arrayEach (node_modules/bizcharts/umd/BizCharts.js:5053:15)
      at Object.forEach [as each] (node_modules/bizcharts/umd/BizCharts.js:13188:16)
      at Group.getBBox (node_modules/bizcharts/umd/BizCharts.js:6148:16)
      at Category._addItem (node_modules/bizcharts/umd/BizCharts.js:46485:26)
      at node_modules/bizcharts/umd/BizCharts.js:46368:12
      at arrayEach (node_modules/bizcharts/umd/BizCharts.js:24622:9)
      at Object.forEach [as each] (node_modules/bizcharts/umd/BizCharts.js:30743:10)
      at Category._renderItems (node_modules/bizcharts/umd/BizCharts.js:46367:10)
      at Category._renderUI (node_modules/bizcharts/umd/BizCharts.js:46026:12)
      at Category.Group (node_modules/bizcharts/umd/BizCharts.js:5938:14)
      at Category.Base (node_modules/bizcharts/umd/BizCharts.js:28142:52)
      at new Category (node_modules/bizcharts/umd/BizCharts.js:45880:51)
      at Group.addGroup (node_modules/bizcharts/umd/BizCharts.js:6007:21)
      at LegendController._addCategroyLegend (node_modules/bizcharts/umd/BizCharts.js:48537:28)
      at LegendController.addLegend (node_modules/bizcharts/umd/BizCharts.js:48642:23)
      at node_modules/bizcharts/umd/BizCharts.js:34525:32
      at arrayEach (node_modules/bizcharts/umd/BizCharts.js:24622:9)
      at Object.forEach [as each] (node_modules/bizcharts/umd/BizCharts.js:30743:10)
      at node_modules/bizcharts/umd/BizCharts.js:34519:16
      at arrayEach (node_modules/bizcharts/umd/BizCharts.js:24622:9)
      at Object.forEach [as each] (node_modules/bizcharts/umd/BizCharts.js:30743:10)
      at Chart._renderLegends (node_modules/bizcharts/umd/BizCharts.js:34516:14)
      at Chart.drawComponents (node_modules/bizcharts/umd/BizCharts.js:34814:12)
      at Chart.render (node_modules/bizcharts/umd/BizCharts.js:35959:10)
      at Chart.render (node_modules/bizcharts/umd/BizCharts.js:34837:28)
      at Processor.createG2Instance (node_modules/bizcharts/umd/BizCharts.js:52978:13)
      at PureChart.componentDidMount (node_modules/bizcharts/umd/BizCharts.js:51692:37)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:8770:24)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:9946:9)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:542:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:581:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:438:27)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:10050:9)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:11017:42)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:10967:7)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:10878:7)
      at scheduleWorkImpl (node_modules/react-dom/cjs/react-dom.development.js:10732:11)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:10689:12)
      at scheduleTopLevelUpdate (node_modules/react-dom/cjs/react-dom.development.js:11193:5)
      at Object.updateContainer (node_modules/react-dom/cjs/react-dom.development.js:11231:7)
      at node_modules/react-dom/cjs/react-dom.development.js:15226:19
      at Object.unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:11102:12)
      at renderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:15225:17)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:15290:12)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:218:50)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:98:16)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Object.it (src/component/eduComponent/genderShare/genderShare.test.js:18:23)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by liunian** [comment]
Works fine with following project settings and run with `npm test`, would you try again or show me your settings?

### scripts and dependencies in `package.json`

> `canvas` module requires `Cairo`, please install them first by following the guides https://github.com/Automattic/node-canvas#compiling

```
{
  "scripts": {
    "test": "mocha --recursive test"
  },
  "dependencies": {
    "@antv/data-set": "^0.8.9",
    "bizcharts": "^3.1.8",
    "react": "^16.4.0",
    "react-dom": "^16.4.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "canvas": "^1.6.11",
    "chai": "^4.1.2",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "jsdom": "^11.11.0",
    "jsdom-global": "^3.0.2",
    "mocha": "^5.2.0"
  }
}
```

### `.babelrc`

```json
{
  "presets": [
    "react",
    "env",
    "stage-0"
  ]
}
```

### `src/pieChart.js`

```jsx
import React from 'react';
import { View as DataView } from '@antv/data-set';
import { Axis, Chart, Coord, Geom, Label, Legend, Tooltip } from 'bizcharts';

export default function PieChart({ data }) {
  const dv = new DataView();
  dv.source(data).transform({
    type: 'percent',
    field: 'count',
    dimension: 'item',
    as: 'percent'
  });
  const cols = {
    percent: {
      formatter: val => {
        val = (val * 100) + '%';
        return val;
      }
    }
  }

  return (
    <Chart height={window.innerHeight} data={dv} scale={cols} padding={[80, 100, 80, 80]} forceFit>
      <Coord type='theta' radius={0.75} />
      <Axis name="percent" />
      <Legend position='right' offsetY={-window.innerHeight / 2 + 120} offsetX={-100} />
      <Tooltip
        showTitle={false}
        itemTpl='<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>'
      />
      <Geom
        type="intervalStack"
        position="percent"
        color='item'
        tooltip={['item*percent', (item, percent) => {
          percent = percent * 100 + '%';
          return {
            name: item,
            value: percent
          };
        }]}
        style={{ lineWidth: 1, stroke: '#fff' }}
      >
        <Label content='percent' offset={-40} textStyle={{
          rotate: 0,
          textAlign: 'center',
          shadowBlur: 2,
          shadowColor: 'rgba(0, 0, 0, .45)'
        }} />
      </Geom>
    </Chart>
  )
}
```

### `test/mocha.opts`

```
-r babel-core/register
-r jsdom-global/register
```

### `test/enzyme.config.js`

```js
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({
  adapter: new Adapter(),
});

export default Enzyme;
```

### `test/pieChart-spec.js`

```jsx
import { assert } from 'chai';
import React from 'react';
import PieChart from "../src/pieChart";
import Enzyme from './enzyme.config';

const { shallow, mount } = Enzyme;

const pieChartData = [
  { item: 'item1', count: 40 },
  { item: 'item2', count: 21 },
  { item: 'item3', count: 17 },
  { item: 'item4', count: 13 },
  { item: 'item5', count: 9 }
];

describe('intervalStack', () => {
  it('Shallow rendering works fine of course', () => {
    shallow(<PieChart data={pieChartData} />);
  });

  it('Mount', () => {
    mount(<PieChart data={pieChartData} />);
  });
});
```
