### ISSUE TITLE
Geom定义color为数组时，jest单测报Error: Uncaught [TypeError: Cannot read property 'width' of undefined]

### ISSUE THREAD

**Issue by helloliduofu** [alibaba/BizCharts#649]
- bizcharts Version:3.4.1
- Platform or react version:16.6.3
- Mini Showcase(like screenshots):
test error infos:
```
 ✓ Statistics render correct (165ms)
  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: Cannot read property 'width' of undefined]
        at reportException (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at invokeEventListeners (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:199:16)
        at invokeGuardedCallback (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:256:31)
        at commitRoot (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:17458:7)
        at completeRoot (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18912:3) TypeError: Cannot read property 'width' of undefined
        at CText.measureText (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:21114:40)
        at CText.calculateBox (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:20956:22)
        at CText.getBBox (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:467:18)
        at /Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:19133:28
        at Object.angle [as each] (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/src/polar.js:151:9)
        at Group.getBBox (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:19127:12)
        at Category._addItem (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:15258:26)
        at /Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:15114:14
        at Object.angle [as each] (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/src/polar.js:151:9)
        at Category._renderItems (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:15113:10)
        at Category.render (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:14892:10)
        at Category.Legend [as constructor] (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:13924:11)
        at new Category (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:14745:20)
        at LegendController._addCategoryLegend (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:32762:18)
        at LegendController.addLegend (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:32957:23)
        at /Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:16849:32
        at Object.angle [as each] (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/src/polar.js:151:9)
        at /Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:16842:16
        at Object.angle [as each] (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/src/polar.js:151:9)
        at Chart._renderLegends (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:16839:14)
        at Chart.drawComponents (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:17133:12)
        at Chart.render (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:34969:10)
        at Chart.render (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:17171:28)
        at Processor.createG2Instance (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:52521:13)
        at PureChart.componentDidMount (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:51099:37)
        at commitLifeCycles (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:15961:22)
        at commitAllLifeCycles (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:17262:7)
        at HTMLUnknownElement.callCallback (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:149:14)
        at invokeEventListeners (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:199:16)
        at invokeGuardedCallback (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:256:31)
        at commitRoot (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:17458:7)
        at completeRoot (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18912:3)
        at performWorkOnRoot (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18841:9)
        at performWork (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18749:7)
        at performSyncWork (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18723:3)
        at requestWork (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18592:5)
        at scheduleWork (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18401:5)
        at scheduleRootUpdate (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19069:3)
        at updateContainerAtExpirationTime (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19097:10)
        at updateContainer (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19154:10)
        at ReactRoot.Object.<anonymous>.ReactRoot.render (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19416:3)
        at /Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19556:14
        at unbatchedUpdates (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18952:10)
        at legacyRenderSubtreeIntoContainer (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19552:5)
        at Object.render (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19613:12)
        at Object.render (/Users/liduofu/Work/dragon/dragon/node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:352:114)
        at new ReactWrapper (/Users/liduofu/Work/dragon/dragon/node_modules/enzyme/build/ReactWrapper.js:130:16)
        at mount (/Users/liduofu/Work/dragon/dragon/node_modules/enzyme/build/mount.js:21:10)
        at Object._callee$ (/Users/liduofu/Work/dragon/dragon/src/modules/statistics/tests/Statistics.test.js:124:21)
        at tryCatch (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
        at Generator.invoke [as _invoke] (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
        at Generator.prototype.(anonymous function) [as next] (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
        at asyncGeneratorStep (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
        at _next (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
        at /Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
        at new Promise (<anonymous>)
        at Object.<anonymous> (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
        at Object.asyncJestTest (/Users/liduofu/Work/dragon/dragon/node_modules/jest-jasmine2/build/jasmine_async.js:108:37)
        at resolve (/Users/liduofu/Work/dragon/dragon/node_modules/jest-jasmine2/build/queue_runner.js:56:12)
        at new Promise (<anonymous>)
        at mapper (/Users/liduofu/Work/dragon/dragon/node_modules/jest-jasmine2/build/queue_runner.js:43:19)
        at promise.then (/Users/liduofu/Work/dragon/dragon/node_modules/jest-jasmine2/build/queue_runner.js:87:41)
        at process._tickCallback (internal/process/next_tick.js:68:7)

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: Cannot read property 'destroy' of undefined]
        at reportException (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at invokeEventListeners (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:199:16)
        at invokeGuardedCallback (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:256:31)
        at safelyCallComponentWillUnmount (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:15806:5)
        at commitUnmount (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:16180:11) TypeError: Cannot read property 'destroy' of undefined
        at Processor.destory (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:52531:18)
        at PureChart.componentWillUnmount (/Users/liduofu/Work/dragon/dragon/node_modules/bizcharts/umd/BizCharts.js:51117:24)
        at callComponentWillUnmountWithTimer (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:15799:12)
        at HTMLUnknownElement.callCallback (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:149:14)
        at invokeEventListeners (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:199:16)
        at invokeGuardedCallback (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:256:31)
        at safelyCallComponentWillUnmount (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:15806:5)
        at commitUnmount (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:16180:11)
        at commitNestedUnmounts (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:16211:5)
        at unmountHostComponents (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:16467:7)
        at commitDeletion (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:16519:5)
        at commitAllHostEffects (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:17214:11)
        at HTMLUnknownElement.callCallback (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:149:14)
        at invokeEventListeners (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/Users/liduofu/Work/dragon/dragon/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:199:16)
        at invokeGuardedCallback (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:256:31)
        at commitRoot (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:17423:7)
        at completeRoot (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18912:3)
        at performWorkOnRoot (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18841:9)
        at performWork (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18749:7)
        at performSyncWork (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18723:3)
        at requestWork (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18592:5)
        at scheduleWork (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18401:5)
        at scheduleRootUpdate (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19069:3)
        at updateContainerAtExpirationTime (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19097:10)
        at updateContainer (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19154:10)
        at ReactRoot.Object.<anonymous>.ReactRoot.render (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19416:3)
        at /Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19556:14
        at unbatchedUpdates (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:18952:10)
        at legacyRenderSubtreeIntoContainer (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19552:5)
        at Object.render (/Users/liduofu/Work/dragon/dragon/node_modules/react-dom/cjs/react-dom.development.js:19613:12)
        at Object.render (/Users/liduofu/Work/dragon/dragon/node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:352:114)
        at new ReactWrapper (/Users/liduofu/Work/dragon/dragon/node_modules/enzyme/build/ReactWrapper.js:130:16)
        at mount (/Users/liduofu/Work/dragon/dragon/node_modules/enzyme/build/mount.js:21:10)
        at Object._callee$ (/Users/liduofu/Work/dragon/dragon/src/modules/statistics/tests/Statistics.test.js:124:21)
        at tryCatch (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
        at Generator.invoke [as _invoke] (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
        at Generator.prototype.(anonymous function) [as next] (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
        at asyncGeneratorStep (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
        at _next (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
        at /Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
        at new Promise (<anonymous>)
        at Object.<anonymous> (/Users/liduofu/Work/dragon/dragon/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
        at Object.asyncJestTest (/Users/liduofu/Work/dragon/dragon/node_modules/jest-jasmine2/build/jasmine_async.js:108:37)
        at resolve (/Users/liduofu/Work/dragon/dragon/node_modules/jest-jasmine2/build/queue_runner.js:56:12)
        at new Promise (<anonymous>)
        at mapper (/Users/liduofu/Work/dragon/dragon/node_modules/jest-jasmine2/build/queue_runner.js:43:19)
        at promise.then (/Users/liduofu/Work/dragon/dragon/node_modules/jest-jasmine2/build/queue_runner.js:87:41)
        at process._tickCallback (internal/process/next_tick.js:68:7)

  console.error node_modules/react-dom/cjs/react-dom.development.js:15749
    The above error occurred in the <PureChart> component:
        in PureChart (created by Chart)
        in div (created by Chart)
        in Chart (created by BChart)
        in ErrorBoundary (created by BChart)
        in BChart (created by Statistics)
        in Statistics (created by WrapperComponent)
        in WrapperComponent

    React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.

  console.error node_modules/react-dom/cjs/react-dom.development.js:15749
    The above error occurred in the <PureChart> component:
        in PureChart (created by Chart)
        in div (created by Chart)
        in Chart (created by BChart)
        in ErrorBoundary (created by BChart)
        in BChart (created by Statistics)
        in Statistics (created by WrapperComponent)
        in WrapperComponent

    React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

- CodePen Link:
code snippet:
```
import React, { Component } from 'react';
import { Chart, Geom, Axis, Tooltip, Coord, Legend } from 'bizcharts';
class Statistics extends Component {
  render() {
    const data = [
      { item: 'PC端', count: 62, percent: 62 },
      { item: '移动端', count: 23, percent: 23 },
      { item: '其他', count: 15, percent: 15 }
    ];
    const opts = { title: '设备占比', alias: '系统' };
    const pieChartData = [];
    data.map(item => {
      pieChartData.push({
        item: item.item + ' ' + item.percent + '%',
        count: item.count,
        percent: item.percent,
        legend: item.item
      });
    });
    const cols = {
      item: {
        alias: opts.title
      },
      percent: {
        alias: '比例',
        formatter: val => {
          return (val = val + '%');
        }
      }
    };
    return (
      <Chart height={340} data={pieChartData} scale={cols} forceFit padding={[40, '25%', 80, '22.5%']}>
        <Tooltip
          showTitle={false}
          itemTpl='<li data-index={index} style="margin-bottom:4px;"><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}<br/><span style="padding-left: 16px">次数：{count}</span><br/><span style="padding-left: 16px">占比：{value}</span><br/></li>'
        />
        <Coord type="theta" radius={0.83} />
        <Axis name="percent" />
        <Legend position="bottom" marker="square" offsetY={-10} itemGap={20} textStyle={{ fontSize: '14' }} />
        <Geom
          type="intervalStack"
          position="percent"
          color={['item', ['#003abc', '#1890ff', '#40a9ff', '#096dd9', '#0050b3', '#69c0ff', '#91d5ff', '#bae7ff']]}
          tooltip={[
            'legend*percent*count',
            (legend, percent, count) => {
              percent = percent + '%';
              return {
                name: legend,
                value: percent,
                count: count
              };
            }
          ]}
        />
      </Chart>
    );
  }
}
export default Statistics;

```
test code:

```
import React from 'react';
import { mount } from 'enzyme';
import Statistics from '../components/Statistics';

test('Statistics render correct', async () => {
const component = mount(
    <Statistics.wrappedComponent/>
  );
  await component.update();
    await component.update();
    await component.update();
});
```

**Comment by weepy3641** [comment]
我直接用你的组件区 render 以及更新并没有问题。
感觉错误像是测试环境中不具备 canvas 的能力，因此使用 canvas 的 measureText 报错了。
所以还需要你确认下

**Comment by helloliduofu** [comment]
> 我直接用你的组件区 render 以及更新并没有问题。
> 感觉错误像是测试环境中不具备 canvas 的能力，因此使用 canvas 的 measureText 报错了。
> 所以还需要你确认下

Jest 统一增加了 许多canvas的方法 ，下面是我的Jest setup文件，只有当我定义颜色成数组时，使用Legend标签，单测才会报错
`// setup file
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
process.on('unhandledRejection', reason => {
  console.warn(reason);
});

// rc-upload 的 key 导致了每次快照 key 都不一样没法 match 修复
// https://github.com/react-component/upload/blob/master/src/uid.js
jest.mock('rc-upload/lib/uid', () => () => 'rc-upload-1');

window.open = () => {};

// Canvas
HTMLCanvasElement.prototype.getContext = () => {
  return {
    fillStyle: null,
    fillRect: () => {},
    drawImage: () => {},
    clearRect: () => {},
    getImageData: () => {},
    putImageData: () => {},
    createImageData: () => {},
    setTransform: () => {},
    save: () => {},
    fillText: () => {},
    restore: () => {},
    beginPath: () => {},
    moveTo: () => {},
    lineTo: () => {},
    closePath: () => {},
    stroke: () => {},
    translate: () => {},
    scale: () => {},
    rotate: () => {},
    arc: () => {},
    fill: () => {},
    measureText: () => {},
    transform: () => {},
    rect: () => {},
    clip: () => {}
  };
};
`

**Comment by areyouse7en** [comment]
canvas需要mock
https://www.npmjs.com/package/jest-canvas-mock
